job/urls.py
from . import views
from django.contrib import admin
from django.urls import path ,include



app_name='job'

urlpatterns = [
    path('',views.job_list ,name='job_list'),
    path('add',views.add_job,name='add_job'),
    path('<int:id>',views.job_detail,name='job_detailurl'),
    
]

project/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('jobs/', include('job.urls',namespace= 'joburl')),
     path('contact-us/', include('contact.urls',namespace= 'contacts')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

job/models.py
from django.db import models
from django_slugify_processor.text import slugify
from django.contrib.auth.models import User
# Create your models here.


'''
    import from moodle for :
    -htmal widget
    -validation
    - db size 

'''

Job_Type=(
    ("Full Time","Full Time"),
    ("Part Time","Part Time"),
    ("On Line","On Line"),

)

def image_upload(inistans , filename):
    imagename , extension = filename.split(".")
    return "pic/%s/%s.%s"%(inistans.id,inistans.id,extension)


class Job(models.Model):  #tabdle

    onwer = models.ForeignKey(User, on_delete=models.CASCADE,related_name='onwer_job')
    title = models.CharField(max_length=100) #column
# we do make migration after create table and coulmn to let django check the table and coulmn able to creat and add to DB and after that we do migrate
    #location
    job_type = models.CharField(max_length=20 , choices= Job_Type)
    descripyion = models.TextField(max_length=1000)
    published_at = models.DateTimeField(auto_now=True)
    Vacancy = models.IntegerField(default=1)
    salary = models.IntegerField(default=0)
    experience = models.IntegerField(default=1)
    category = models.ForeignKey('Category',on_delete=models.CASCADE)
    image = models.ImageField(upload_to=image_upload)
    slug = models.SlugField(blank=True , null= True)




    def save(self,*args ,**kwargs):
        self.slug = slugify(self.title) 
        #logic
        super(Job,self).save(*args,**kwargs)


    #return name of job in admin panal
    def __str__(self):
        return self.title



class Category(models.Model):
    Name = models.CharField(max_length=25)


    def __str__(self):
        return self.Name


class apply(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE,related_name='apply_job')
    name = models.CharField(max_length=30)
    email = models.EmailField(max_length=100)
    websit = models.URLField()
    cv = models.FileField(upload_to='apply/')
    cover_leteer = models.TextField(max_length=500)
    created_at =models.DateTimeField(auto_now=True)



    def __str__(self):
        return self.name
    

job/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from .models import Job
from django.core.paginator import Paginator
from .form import applyform ,JobForm
from django.contrib.auth.decorators import login_required
from .filters import JobFilters


    
# Create your views here.


def job_list(request):
    job_list = Job.objects.all()


    myfilter = JobFilters(request.GET,queryset=job_list)
    job_list = myfilter.qs

    paginator = Paginator(job_list, 5) # Show 25 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context={'jobs': page_obj ,'myfilter':myfilter}
    return render(request,'job/job_list.html',context)

   


def job_detail(request , id):
    job_detail = Job.objects.get(id=id)

    if request.method=='POST':
      form = applyform(request.POST ,request.FILES)
      if form.is_valid():
          myform =form.save(commit=False)
          myform.job= job_detail
          myform.save()


    else:
        form = applyform()
    context={'job': job_detail ,'form':form}
    return render(request,'job/job_detail.html',context)


@login_required
def add_job(request):
   if request.method=='POST':
       form = JobForm(request.POST ,request.FILES)
       if form.is_valid():
          myform =form.save(commit=False)
          myform.onwer= request.user
          myform.save()
          return redirect(reverse('joburl:job_list'))
   else:
       form =JobForm()
   

   return render(request,'job/add_job.html',{'form':form})

        

job/templates/job/job_detail.html
{% extends 'base.html' %}   
{% load bootstrap4 %}
    {% block body %}

     <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{job.title}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                                <div class="thumb">
                                    <img src="{{job.image.url}}" alt=""  style="max-width:60px;">
                                </div>
                                <div class="jobs_conetent">
                                    <a href="#"><h4>{{job.title}}</h4></a>
                                    <div class="links_locat d-flex align-items-center">
                                        <div class="location">
                                            <p> <i class="fa fa-map-marker"></i> California, USA</p>
                                        </div>
                                        <div class="location">
                                            <p> <i class="fa fa-clock-o"></i>{{job.job_type}}   </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="jobs_right">
                                <div class="apply_now">
                                    <a class="heart_mark" href="#"> <i class="ti-heart"></i> </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="descript_wrap white-bg">
                        <div class="single_wrap">
                            <h4>Job description</h4>
                            <p>{{job.descripyion}}</p>
                        </div>
                        <div class="single_wrap">
                            <h4>Responsibility</h4>
                            <ul>
                                <li>The applicants should have experience in the following areas.
                                </li>
                                <li>Have sound knowledge of commercial activities.</li>
                                <li>Leadership, analytical, and problem-solving abilities.</li>
                                <li>Should have vast knowledge in IAS/ IFRS, Company Act, Income Tax, VAT.</li>
                            </ul>
                        </div>
                        <div class="single_wrap">
                            <h4>Qualifications</h4>
                            <ul>
                                <li>The applicants should have experience in the following areas.
                                </li>
                                <li>Have sound knowledge of commercial activities.</li>
                                <li>Leadership, analytical, and problem-solving abilities.</li>
                                <li>Should have vast knowledge in IAS/ IFRS, Company Act, Income Tax, VAT.</li>
                            </ul>
                        </div>
                        <div class="single_wrap">
                            <h4>Benefits</h4>
                            <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing.</p>
                        </div>
                    </div>
                    <div class="apply_job_form white-bg">
                        <h4>Apply for the job</h4>
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                            {% buttons %}
                               <button class="boxed-btn3 w-100" type="submit">Apply Now</button>
                            {% endbuttons %}
                        </form>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Job Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Published on: <span>{{job.published_at| date:'d M o'}}</span></li>
                                <li>Vacancy: <span>{{job.Vacancy}} Position</span></li>
                                <li>Salary: <span> {{job.salary}} $</span></li>
                                <li>Location: <span>California, USA</span></li>
                                <li>Job Nature: <span>{{job.job_type}}</span></li>
                            </ul>
                        </div>
                    </div>
                    <div class="share_wrap d-flex">
                        <span>Share at:</span>
                        <ul>
                            <li><a href="#"> <i class="fa fa-facebook"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-google-plus"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-twitter"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-envelope"></i></a> </li>
                        </ul>
                    </div>
                    <div class="job_location_wrap">
                        <div class="job_lok_inner">
                            <div id="map" style="height: 200px;"></div>
                            <script>
                              function initMap() {
                                var uluru = {lat: -25.363, lng: 131.044};
                                var grayStyles = [
                                  {
                                    featureType: "all",
                                    stylers: [
                                      { saturation: -90 },
                                      { lightness: 50 }
                                    ]
                                  },
                                  {elementType: 'labels.text.fill', stylers: [{color: '#ccdee9'}]}
                                ];
                                var map = new google.maps.Map(document.getElementById('map'), {
                                  center: {lat: -31.197, lng: 150.744},
                                  zoom: 9,
                                  styles: grayStyles,
                                  scrollwheel:  false
                                });
                              }
                              
                            </script>
                            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap"></script>
                            
                          </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    {% endblock body %}
   
                                           


   

job/templates/job/job_list.html
{% extends "base.html" %}
{% load bootstrap4 %}



  {% block body %}

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{jobs.count}}+ Jobs Available</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <!-- job_listing_area_start  -->
    <div class="job_listing_area plus_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="job_filter white-bg">
                        <div class="form_inner white-bg">
                            <h3>Filter</h3>
                            <form method="GET">
                               {% bootstrap_form myfilter.form %}
                               <input type="submit" value="search" class="boxed-btn3 w-100 mt-2">

                            </form>
                        </div>

                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="recent_joblist_wrap">
                        <div class="recent_joblist white-bg ">
                            <div class="row align-items-center">
                                <div class="col-md-6">
                                    <h4>Job Listing</h4>
                                </div>
                                <div class="col-md-6">
                                    <div class="serch_cat d-flex justify-content-end">
                                        <select>
                                            <option data-display="Most Recent">Most Recent</option>
                                            <option value="1">Marketer</option>
                                            <option value="2">Wordpress </option>
                                            <option value="4">Designer</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="job_lists m-0">
                        <div class="row">
                        {% for job in jobs %}
                            <div class="col-lg-12 col-md-12">
                                <div class="single_jobs white-bg d-flex justify-content-between">
                                    <div class="jobs_left d-flex align-items-center">
                                        <div class="thumb">
                                            <img src="{{job.image.url}}" alt=""  style="max-width:60px;">
                                        </div>
                                        <div class="jobs_conetent">
                                            <a href="{% url 'joburl:job_detailurl' job.id%}"><h4>{{job.title}}</h4></a>
                                            <div class="links_locat d-flex align-items-center">
                                                <div class="location">
                                                    <p> <i class="fa fa-map-marker"></i> California, USA</p>
                                                </div>
                                                <div class="location">
                                                    <p> <i class="fa fa-clock-o"></i>{{job.job_type}}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="jobs_right">
                                        <div class="apply_now">
                                            <a class="heart_mark" href="#"> <i class="fa fa-heart"></i> </a>
                                            <a href="{% url 'joburl:job_detailurl' job.id%}" class="boxed-btn3">Apply Now</a>
                                        </div>
                                        <div class="date">
                                            <p>{{job.published_at| date:'d/m/o'}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {%endfor %}
                        </div>
                        {% if  jobs.has_other_pages%}
                         <div class="row">
                            <div class="col-lg-12">
                                <div class="pagination_wrap">
                                    <ul>
                                        {% if jobs.has_previous %}
                                        <li><a href="?page={{jobs.previous_page_number}}"> <i class="ti-angle-left"></i> </a></li>
                                         {% endif %}

                                        {%for i in jobs.paginator.page_range%}
                                        <li><a href="?page={{i}}"><span>{{i}}</span></a></li>
                                        {%endfor %}
                                        {% if jobs.has_next %}
                                        <li><a href="?page={{jobs.next_page_number}}"> <i class="ti-angle-right"></i> </a></li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                         {% endif %}

                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- job_listing_area_end  -->
  {% endblock body %}

   