accounts/urls.py
from . import views
from django.contrib import admin
from django.urls import path ,include



app_name='accounts'

urlpatterns = [
    path('signup',views.signup ,name='signup'),
    path('profile',views.Profile ,name='profile'),
    path('login',views.login ,name='login'),
    path('logout',views.logout ,name='logout'),

    path('profile/edit',views.profile_edit ,name='profile_edit'),
   
    
]

job/urls.py
from . import views
from django.contrib import admin
from django.urls import path ,include



app_name='job'

urlpatterns = [
    path('',views.job_list ,name='job_list'),
    path('add',views.add_job,name='add_job'),
    path('<int:id>',views.job_detail,name='job_detailurl'),
    
]

project/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('jobs/', include('job.urls',namespace= 'joburl')),
     path('contact-us/', include('contact.urls',namespace= 'contacts')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.




class profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(null=True, max_length=50)
    last_name = models.CharField(null=True, max_length=50)
    phone_number =  models.CharField(max_length=15)
    image = models.ImageField(upload_to="profile/")
    city_name = models.ForeignKey("city",on_delete=models.CASCADE , null=True)

    def __str__(self):
        return str(self.user)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        profile.objects.create(user=instance)


class city(models.Model):
    name = models.CharField( max_length=20)

    def __str__(self):
        return str(self.name)

accounts/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import profile




class SignupForm(UserCreationForm):
   class Meta:
        model = User
        fields = ['username','email','password1','password2']




class UserForm(ModelForm):
    
    class Meta:
        model = User
        fields = ["username","first_name","last_name","email"]


class ProfileForm(ModelForm):
    class Meta:
       model = profile
       fields = ["phone_number","city_name","image"]
       
        

accounts/views.py
from django.shortcuts import render,redirect,reverse
from .forms import SignupForm ,UserForm,ProfileForm
from django.contrib.auth import authenticate ,login
from accounts.models import profile

# Create your views here.



def signup(request):
    if request.method=="POST":
        form = SignupForm(request.POST)
        if form.is_valid():
           form.save()
           username = form.cleaned_data['username']
           password = form.cleaned_data['password1']
           user = authenticate(username=username, password=password)
           login(request, user)
           return redirect(reverse('registration/login_register.html'))

        
    else:
        form = SignupForm()


    
    return render(request,'registration/signup.html',{'form':form})






def Profile(request):
    Profile = profile.objects.get(user=request.user)
    return render(request,'accounts/profile.html',{'Profile':Profile})




def profile_edit(request):
    profilee = profile.objects.get(user=request.user)
    if request.method=="POST":
         userform = UserForm(request.POST,instance=request.user)
         profileform = ProfileForm(request.POST,request.FILES,instance=profilee )
         if userform.is_valid() and profileform.is_valid():
             userform.save()
             myprofile= profileform.save(commit=False)
             myprofile.user= request.user
             myprofile.save()
             return redirect(reverse('accounts:profile'))
        
        
    else:
         userform=UserForm(instance=request.user)
         profileform = ProfileForm(instance=profilee)
        
    return render(request,'accounts/profile_edit.html',{'userform':userform , 'profileform':profileform})


def login(request):
        return redirect(reverse('templates/registration/login.html'))


def logout(request):
        return redirect(reverse('templates/registration/logout.html'))

accounts/templates/accounts/profile.html
{% extends 'base.html' %}   
{% load bootstrap4 %}
    {% block body %}

     <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{job.title}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Profile Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Name: <span>{{Profile.user}}</span></li>
                                <li>Email: <span>{{Profile.user.email}} </span></li>
                                <li>Phone: <span> {{Profile.phone_number}} </span></li>
                                <li>Addres: <span>{{Profile.city_name}}</span></li>
                            </ul>
                            
                        </div>
                    </div class="p-5">
                    <a href="{% url 'accounts:profile_edit'%}" class="boxed-btn3 w-100">Edite Profile</a>
                   <div>
                   </div>
                    
                </div>
            </div>
        </div>
    </div>
    
    {% endblock body %}
   
                                           


   

accounts/templates/accounts/profile_edit.html
{% extends 'base.html' %}   
{% load bootstrap4 %}
    {% block body %}

     <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">                           
                    <div class="apply_job_form white-bg">
                        <h4>Edite Profile</h4>
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form userform %}
                            {% bootstrap_form profileform %}

                            {% buttons %}
                               <button class="boxed-btn3 w-100" type="submit">Save</button>
                            {% endbuttons %}
                        </form>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
    
    {% endblock body %}
   
                                           


   